title: Ionic POS app
description: Hybrid mobile POS app, based on Ionic 4, Angular 8
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
github:
  apk_url: assets/POSapp.apk
  src_url: https://codecanyon.net/item/ionic-pos-app-manage-orders-menu-items-print-bills/25773625
  owner_name: Ngoc L.B
  owner_url: https://ngoclb.com