title: Ionic POS App
description: Hybrid Mobile POS Application, based on Ionic 4 & Angular 8
show_downloads: true
google_analytics: UA-109033808-3
theme: jekyll-theme-leap-day
github:
  apk_url: assets/Ionic-PoS-App.apk
  src_url: https://ngoclb.com/ionic-pos-app-src
  owner_name: Ngoc L.B
  owner_url: https://ngoclb.com